# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='sketchy',
  serialized_pb=_b('\n\x0emessages.proto\x12\x07sketchy\"\x1f\n\x10\x42loomObservation\x12\x0b\n\x03key\x18\x01 \x01(\t\"@\n\nBloomMerge\x12\r\n\x05width\x18\x01 \x01(\x05\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\x05\x12\x14\n\x0cones_indices\x18\x03 \x03(\x05\"j\n\x0fReservoirUpdate\x12/\n\x04keys\x18\x01 \x03(\x0b\x32!.sketchy.ReservoirUpdate.KeyValue\x1a&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\x01\x12\r\n\x05value\x18\x02 \x01(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BLOOMOBSERVATION = _descriptor.Descriptor(
  name='BloomObservation',
  full_name='sketchy.BloomObservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='sketchy.BloomObservation.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=58,
)


_BLOOMMERGE = _descriptor.Descriptor(
  name='BloomMerge',
  full_name='sketchy.BloomMerge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='sketchy.BloomMerge.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='depth', full_name='sketchy.BloomMerge.depth', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ones_indices', full_name='sketchy.BloomMerge.ones_indices', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=124,
)


_RESERVOIRUPDATE_KEYVALUE = _descriptor.Descriptor(
  name='KeyValue',
  full_name='sketchy.ReservoirUpdate.KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='sketchy.ReservoirUpdate.KeyValue.key', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='sketchy.ReservoirUpdate.KeyValue.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=232,
)

_RESERVOIRUPDATE = _descriptor.Descriptor(
  name='ReservoirUpdate',
  full_name='sketchy.ReservoirUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='sketchy.ReservoirUpdate.keys', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESERVOIRUPDATE_KEYVALUE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=232,
)

_RESERVOIRUPDATE_KEYVALUE.containing_type = _RESERVOIRUPDATE
_RESERVOIRUPDATE.fields_by_name['keys'].message_type = _RESERVOIRUPDATE_KEYVALUE
DESCRIPTOR.message_types_by_name['BloomObservation'] = _BLOOMOBSERVATION
DESCRIPTOR.message_types_by_name['BloomMerge'] = _BLOOMMERGE
DESCRIPTOR.message_types_by_name['ReservoirUpdate'] = _RESERVOIRUPDATE

BloomObservation = _reflection.GeneratedProtocolMessageType('BloomObservation', (_message.Message,), dict(
  DESCRIPTOR = _BLOOMOBSERVATION,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:sketchy.BloomObservation)
  ))
_sym_db.RegisterMessage(BloomObservation)

BloomMerge = _reflection.GeneratedProtocolMessageType('BloomMerge', (_message.Message,), dict(
  DESCRIPTOR = _BLOOMMERGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:sketchy.BloomMerge)
  ))
_sym_db.RegisterMessage(BloomMerge)

ReservoirUpdate = _reflection.GeneratedProtocolMessageType('ReservoirUpdate', (_message.Message,), dict(

  KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), dict(
    DESCRIPTOR = _RESERVOIRUPDATE_KEYVALUE,
    __module__ = 'messages_pb2'
    # @@protoc_insertion_point(class_scope:sketchy.ReservoirUpdate.KeyValue)
    ))
  ,
  DESCRIPTOR = _RESERVOIRUPDATE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:sketchy.ReservoirUpdate)
  ))
_sym_db.RegisterMessage(ReservoirUpdate)
_sym_db.RegisterMessage(ReservoirUpdate.KeyValue)


# @@protoc_insertion_point(module_scope)
